# 1. H2 DB ?? ?? ?? (??? ? ????? pkproject_db ?? ??)
spring.datasource.url=jdbc:h2:file:~/PKproject/pkproject_db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. JPA ?? (H2 ?? ?? ? ?? ??)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

# 3. ??: ?? ??? ? ??? ?? (create -> update ??)
spring.jpa.hibernate.ddl-auto=update